### ISSUE TITLE
Setting Event->optOut causes exception

### ISSUE THREAD

**Issue by volman-dev** [Setono/meta-conversions-api-php-sdk#6]
Exception is raised when executing following:

```
$event = new Event(Event::EVENT_VIEW_CONTENT);
// ... more settings
$event->optOut = true;

$client = new Client();
$client->sendEvent($event); // Exception raised here
```

Exception: `'Expected an array. Got: boolean' in 'vendor/webmozart/assert/src/Assert.php' line 2074`
Stack trace:
```
#1 vendor/setono/meta-conversions-api-php-sdk/src/Event/Parameters.php(89): Webmozart\Assert\Assert::isArray(true)
#2 vendor/setono/meta-conversions-api-php-sdk/src/Event/Parameters.php(96): Setono\MetaConversionsApi\Event\Parameters::normalize(true, 'opt_out')
#3 vendor/setono/meta-conversions-api-php-sdk/src/Event/Parameters.php(23): Setono\MetaConversionsApi\Event\Parameters::normalize(Array)
#4 vendor/setono/meta-conversions-api-php-sdk/src/Client/Client.php(49): Setono\MetaConversionsApi\Event\Parameters->getPayload()
```

**Comment by loevgaard** [comment]
Hi, @volman-dev 

Thank you for reporting this. Are you able to

1. create a failing test,
2. create a PR,

or both? :-)

**Comment by volman-dev** [comment]
Hi @loevgaard ,

Here is a patch for the existing test. It raises exception even beforethe assertion:

[6-event-test-opt-out.patch](https://github.com/Setono/meta-conversions-api-php-sdk/files/11277098/6-event-test-opt-out.patch)

Hope it helps  : )
